### ISSUE TITLE
graphql schema import Error: Type “Contact” not found in document

### ISSUE THREAD

**Issue by dilipkumar2k6** [graphcool/graphql-import#152]
I use `graphql-import` to load graphql schema written in separate file. I have more than 40+ individual schema files however with surprise it doesn't recognize `Contact` type I have. Following are more details.
```Javascript
// contact.graphql
type Contact {
    firstName: String
    lastName: String
    email: String!
    phoneNumber: String
}

// seller.graphql
# import Contact from './contact.graphql'
type Seller {
  sellerId: String!
  name: String
  image: String
  contact: Contact # Somehow not able to find Contact type
}
```
Note: contact.graphql and seller.graphql are in same directory

Following is code to import schema.
```Javascript
const { importSchema } = require('graphql-import');

// Load GraphQL schema from files
const typeDefs = importSchema('./typedef/index.graphql');
```

While running server, I get following error. I have no clue why? Any help will be appreciated.
```Javascript
/Users/****/workspace/my-project//node_modules/graphql/utilities/buildASTSchema.js:134
    throw new Error('Type "' + typeRef.name.value + '" not found in document.');
    ^

Error: Type "Contact" not found in document.
    at ASTDefinitionBuilder._resolveType (/Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:134:11)
    at ASTDefinitionBuilder.buildType (/Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:218:79)
    at ASTDefinitionBuilder._buildWrappedType (/Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:227:24)
    at ASTDefinitionBuilder.buildField (/Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:248:18)
    at /Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:302:21
    at /Users/****/workspace/my-project/node_modules/graphql/jsutils/keyValMap.js:28:31
    at Array.reduce (<anonymous>)
    at keyValMap (/Users/****/workspace/my-project/node_modules/graphql/jsutils/keyValMap.js:27:15)
    at ASTDefinitionBuilder._makeFieldDefMap (/Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:299:49)
    at fields (/Users/****/workspace/my-project/node_modules/graphql/utilities/buildASTSchema.js:284:23)
```

**Comment by dilipkumar2k6** [comment]
Everything started working fine when I exported below into my index.graphql.

```Javascript
schema {
  query: Query
  mutation: Mutation
}
```
Seems like I was missing this basic.

**Comment by dilipkumar2k6** [comment]
After going through my big schema list, I realized that two `graphql` file has same schema name as `Seller` (in different location) that was causing conflict. 

Learning is, even we can organize `graphql` files into different logical directory structure, but we have to keep unique `type` :-)
