### ISSUE TITLE
Cyclic Dependencies

### ISSUE THREAD

**Issue by schie** [graphcool/graphql-import#6]
Hello!

I'm running into an issue possibly related to _cyclic dependencies_. Any Help would be really appreciated.

#### Example files
Here's a simple example of what I'm trying to do:

```graphql
# a.graphql
# import B from "b.graphql"

type A {
someField: String!
bs: [B]
}
```

```graphql
# b.graphql
# import A from "a.graphql"

type B {
someField: String!
a: A
}
```

#### Error
Here's the error I'm getting once I start the application. Am I doing something wrong?
```bash
/path/to/project/node_modules/graphql-import/node_modules/graphql/index.js:330
    return _language.parse;
                    ^

RangeError: Maximum call stack size exceeded
    at Object.get [as parse] (/path/to/project/node_modules/graphql-import/node_modules/graphql/index.js:330:21)
    at collectDefinitions (/path/to/project/node_modules/graphql-import/dist/index.js:39:29)
    at /path/to/project/node_modules/graphql-import/dist/index.js:43:16
    at Array.map (native)
    at collectDefinitions (/path/to/project/node_modules/graphql-import/dist/index.js:41:63)
    at /path/to/project/node_modules/graphql-import/dist/index.js:43:16
    at Array.map (native)
    at collectDefinitions (/path/to/project/node_modules/graphql-import/dist/index.js:41:63)
    at /path/to/project/node_modules/graphql-import/dist/index.js:43:16
    at Array.map (native)
    at collectDefinitions (/path/to/project/node_modules/graphql-import/dist/index.js:41:63)
    at /path/to/project/node_modules/graphql-import/dist/index.js:43:16
    at Array.map (native)
    at collectDefinitions (/path/to/project/node_modules/graphql-import/dist/index.js:41:63)
    at /path/to/project/node_modules/graphql-import/dist/index.js:43:16
    at Array.map (native)
error Command failed with exit code 1.
```

It will run start and run as expected if the types are in the same file, but I have quite a few types with a large number of fields, so I would like to keep things broken-out as a file for each type.

Any thoughts?

thanks!

**Comment by schickling** [comment]
Hi @schie that definitely looks like a bug. Would be great if you (or someone else) create a PR for this adding some new tests and a fix. 🙌

**Comment by schie** [comment]
@schickling I'll try to take a crack at it 😄
