### ISSUE TITLE
Incorrect import with typescript.

### ISSUE THREAD

**Issue by giautm** [graphcool/graphql-import#7]
I have to do this to make this module works (https://github.com/apollographql/graphql-tools/issues/273#issuecomment-281481217)
```typescript
import { importSchema } from 'graphql-import';
import * as path from 'path';

export const typeDefs = importSchema(path.join(__dirname, './schema.graphql'));
```

if I did as the example, i will be got:
```bash

    ENOENT: no such file or directory, open 'schema.graphql'

      at Object.fs.openSync (fs.js:646:18)
      at Object.fs.readFileSync (fs.js:551:33)
      at read (node_modules/graphql-import/dist/index.js:8:37)
      at Object.importSchema (node_modules/graphql-import/dist/index.js:29:15)
      at Object.<anonymous> (src/graphql/index.ts:9:37)
      at Object.<anonymous> (src/graphql/__tests__/schema.test.ts:3:15)
```

node: v8.9.1
npm: 5.5.1

**Comment by kbrandwijk** [comment]
This is unrelated to `graphql-import`, but has to do with resolving file paths when building typescript.
